### ISSUE TITLE
Publish on jcenter, maven central, etc.?

### ISSUE THREAD

**Issue by colindean** [david-w-millar/gcolors#1]
I'd love to use gcolors in a project. It would be a lot easier for me if it was in a repository somewhere.

I found that you've [previously published things to jcenter](http://jcenter.bintray.com/org/millarts/) but it doesn't have gcolors. It's not in Maven Central, either.

**Comment by david-w-millar** [comment]
Hi there!  Sorry for the insanely delayed response.  I must have missed the notification for this issue.

I'm working on publishing it to jcenter right now - for the same reason.  It should be up by the end of the day.  Thanks for checking the project out!

**Comment by david-w-millar** [comment]
Hey @colindean , 

I've published gcolors on bintray [here](https://bintray.com/david-w-millar/maven/gcolors).

I'm going to close this issue for now.  Let me know if you have any issues.

**Comment by colindean** [comment]
Thank you! Now, to remember what I was going to do with it. I think I wanted to make one of my builds more... colorful.

**Comment by david-w-millar** [comment]
:laughing: IIRC, that's the same reason that I wrote this.
